"use client";

import { useMemo, useState } from "react";
import "@/app/workbench-overrides.css";
import { GraphMap, type GraphViewMode } from "@/app/graph-map";
import type { MoneyData, MoneyNode } from "@/lib/money-data";
import type { InvestigationRoute } from "@/lib/investigation-data";
import { InvestigationPanel } from "@/app/investigation-panel";

export type Language = "ru" | "en";
const ROLES = ["consolidator", "coordinator", "distributor", "transit", "terminal", "peripheral"] as const;
const ROLE_LABEL: Record<Language, Record<string, string>> = {
  ru: { consolidator: "Сборщик", coordinator: "Координатор", distributor: "Распределитель", transit: "Транзит", terminal: "Конечный", peripheral: "Периферийный" },
  en: { consolidator: "Consolidator", coordinator: "Coordinator", distributor: "Distributor", transit: "Transit", terminal: "Terminal", peripheral: "Peripheral" },
};
const T = {
  ru: { accounts:"Счета",clusters:"Кластеры",method:"Методика",search:"Найти GID",queue:"Очередь проверки",filter:"Фильтры",all:"Все роли",show:"Показать связи на графе",network:"Вся сеть",links:"Связи счёта",cluster:"Кластер",whyPriority:"Почему проверить",whyRole:"Почему эта роль",technical:"Технические детали",priority:"Приоритет проверки",role:"Роль",inflow:"Получено",outflow:"Отправлено",counterparties:"Контрагенты",depth:"Глубина",limitations:"Ограничения данных",limitationsText:"Переводы меньше 5 000 KZT не видны; дальнейшие переводы узлов глубины 4 могут отсутствовать.",high:"Высокий",elevated:"Повышенный",medium:"Умеренный",low:"Низкий",select:"Выберите счёт из очереди или на карте",matches:"счетов",reset:"Сбросить",top:"Приоритетные счета",advanced:"Формальное правило и метрики",internal:"Внутренний оборот",seeds:"Seed-счета",openCluster:"Открыть кластер",methodText:"Роли назначаются детерминированными правилами. Приоритет помогает выбрать порядок проверки и не является обвинением. Направление и суммы переводов сохраняются; только Louvain-кластеризация использует неориентированную проекцию.",dataStatus:"2 248 счетов · 3 119 направленных связей",hypothesis:"Гипотеза"},
  en: { accounts:"Accounts",clusters:"Clusters",method:"Method",search:"Find GID",queue:"Review queue",filter:"Filters",all:"All roles",show:"Show links on graph",network:"Full network",links:"Account links",cluster:"Cluster",whyPriority:"Why review",whyRole:"Why this role",technical:"Technical details",priority:"Review priority",role:"Role",inflow:"Received",outflow:"Sent",counterparties:"Counterparties",depth:"Depth",limitations:"Data limitations",limitationsText:"Transfers below 5,000 KZT are not visible; onward transfers for depth-4 nodes may be absent.",high:"High",elevated:"Elevated",medium:"Moderate",low:"Low",select:"Choose an account from the queue or map",matches:"accounts",reset:"Reset",top:"Prioritized accounts",advanced:"Formal rule and metrics",internal:"Internal turnover",seeds:"Seed accounts",openCluster:"Open cluster",methodText:"Roles are assigned by deterministic rules. Priority orders review and is not an allegation. Transfer direction and amounts are preserved; only Louvain clustering uses an undirected projection.",dataStatus:"2,248 accounts · 3,119 directed links",hypothesis:"Hypothesis"},
} as const;

const num = (v:number,l:Language) => new Intl.NumberFormat(l === "ru" ? "ru-RU" : "en-US").format(v);
const money = (v:number,l:Language) => `${num(Math.round(v),l)} KZT`;
export function priorityColor(score:number) { return score >= .85 ? "#d64545" : score >= .7 ? "#ea7a32" : score >= .5 ? "#e7b52c" : score >= .25 ? "#a8b83a" : "#35a65a"; }
function priorityLabel(score:number,l:Language) { const t=T[l]; return score >= .85 ? t.high : score >= .7 ? t.elevated : score >= .5 ? t.medium : score >= .25 ? (l === "ru" ? "Невысокий" : "Limited") : t.low; }
function roleReason(n:MoneyNode,l:Language) {
  const ru:Record<string,string>={coordinator:`Счёт находится на значимом числе направленных маршрутов и может связывать разные участки движения средств.`,consolidator:`Средства поступают от ${n.in_deg} отправителей и концентрируются на меньшем числе исходящих направлений.`,distributor:`Счёт распределяет средства между ${n.out_deg} получателями.`,transit:`Входящий и исходящий оборот близки: отношение составляет ${n.pass_through?.toFixed(2) ?? "—"}.`,terminal:`В наблюдаемой части графа счёт получил средства, но дальнейших переводов не видно.`,peripheral:`Поведение счёта не достигло порогов специальных ролей.`};
  const en:Record<string,string>={coordinator:"The account lies on a meaningful share of directed paths and may connect different parts of the observed flow.",consolidator:`Funds arrive from ${n.in_deg} senders and narrow into fewer outgoing directions.`,distributor:`The account distributes funds to ${n.out_deg} recipients.`,transit:`Observed inflow and outflow are close: the ratio is ${n.pass_through?.toFixed(2) ?? "—"}.`,terminal:"The account received funds with no observed onward transfer in the available graph.",peripheral:"The account did not meet a specialized role threshold."};
  return (l === "ru" ? ru : en)[n.role];
}
function priorityHeading(score:number,l:Language) {
  if (l === "ru") return score < .25 ? "Почему приоритет низкий" : score < .5 ? "Почему стоит наблюдать" : "Почему проверить";
  return score < .25 ? "Why priority is low" : score < .5 ? "Why monitor" : "Why review";
}
function priorityReason(n:MoneyNode,l:Language) {
  const amount=n.is_seed ? n.out_kzt : Math.max(n.in_kzt,n.out_kzt), cp=n.distinct_counterparties;
  if (l === "ru") {
    const counterparties = `${cp} ${cp % 10 === 1 && cp % 100 !== 11 ? "контрагент" : cp % 10 >= 2 && cp % 10 <= 4 && (cp % 100 < 12 || cp % 100 > 14) ? "контрагента" : "контрагентов"}`;
    const facts = `наблюдаемый ${n.is_seed || n.out_kzt > n.in_kzt ? "исходящий" : "входящий"} оборот ${money(amount,l)}, ${n.is_seed ? `${cp} получателей` : counterparties}, глубину ${n.depth}, взвешенный по сумме PageRank ${n.pagerank.toFixed(6)} и роль «${ROLE_LABEL.ru[n.role]}»`;
    if (n.priority_score < .25) return `Приоритет низкий по текущим правилам; неполные данные могут скрывать активность. Оценка учитывает ${facts}.`;
    if (n.priority_score < .5) return `Счёт не относится к первоочередным, но его стоит оставить под наблюдением. Оценка учитывает ${facts}.`;
    return `Счёт поднят в очереди проверки: оценка учитывает ${facts}.`;
  }
  const facts = `observed ${n.is_seed || n.out_kzt > n.in_kzt ? "outflow" : "inflow"} of ${money(amount,l)}, ${cp} ${n.is_seed ? "recipients" : "distinct counterparties"}, hop ${n.depth}, amount-weighted PageRank ${n.pagerank.toFixed(6)}, and the ${ROLE_LABEL.en[n.role]} role`;
  if (n.priority_score < .25) return `Priority is low under the current rules; incomplete data may conceal activity. The score reflects ${facts}.`;
  if (n.priority_score < .5) return `The account is not an immediate priority, but remains worth monitoring. The score reflects ${facts}.`;
  return `The account is elevated in the review queue. The score reflects ${facts}.`;
}

export function MoneyWorkbench({data}:{data:MoneyData|null}) {
  const [lang,setLang]=useState<Language>("ru"), [page,setPage]=useState<"accounts"|"clusters"|"method">("accounts");
  const [selected,setSelected]=useState<string|null>(()=>data ? [...data.nodes].sort((a,b)=>b.priority_score-a.priority_score||a.gid.localeCompare(b.gid))[0]?.gid ?? null:null);
  const [graphMode,setGraphMode]=useState<GraphViewMode>("connections"), [focusToken,setFocusToken]=useState(0), [query,setQuery]=useState(""), [roleFilter,setRoleFilter]=useState("all"), [filters,setFilters]=useState(false);
  const [inspectorOpen,setInspectorOpen]=useState(true), [activeRoute,setActiveRoute]=useState<InvestigationRoute|null>(null);
  const [searchOpen,setSearchOpen]=useState(false), [activeSuggestion,setActiveSuggestion]=useState(0);
  const t=T[lang], graph=data?.graph;
  const nodes=useMemo(()=>data?.nodes??[],[data]);
  const clusters=useMemo(()=>data?.clusters??[],[data]);
  const byGid=useMemo(()=>new Map(nodes.map(n=>[n.gid,n])),[nodes]);
  const ordered=useMemo(()=>[...nodes].filter(n=>roleFilter==="all"||n.role===roleFilter).sort((a,b)=>b.priority_score-a.priority_score||a.gid.localeCompare(b.gid)),[nodes,roleFilter]);
  const selectedNode=selected ? byGid.get(selected)??null:null;
  const suggestions=useMemo(()=>query ? nodes.filter(n=>n.gid.includes(query)).sort((a,b)=>Number(b.gid.startsWith(query))-Number(a.gid.startsWith(query))).slice(0,7):[],[nodes,query]);
  const rankedClusters=useMemo(()=>[...clusters].sort((a,b)=>b.sum_kzt_internal-a.sum_kzt_internal||a.cluster_id-b.cluster_id),[clusters]);
  function choose(gid:string){if(!byGid.has(gid))return;setSelected(gid);setQuery(gid);setSearchOpen(false);setInspectorOpen(true);setActiveRoute(null);if(graphMode==="route"||page!=="accounts")setGraphMode("connections");setPage("accounts");}
  function focus(mode:GraphViewMode){setGraphMode(mode);if(mode!=="route")setActiveRoute(null);setFocusToken(v=>v+1);setPage("accounts");}
  function showRoute(route:InvestigationRoute){setActiveRoute(route);setGraphMode("route");setFocusToken(v=>v+1);}
  if(!data||!graph) return <main className="empty-state"><h1>Money Graph</h1><p>Run the pipeline first.</p></main>;
  return <div className="app-shell">
    <header className="app-header"><button className="wordmark" onClick={()=>setPage("accounts")}><span>⌁</span><b>Money Graph</b></button><nav><button className={page==="accounts"?"active":""} onClick={()=>setPage("accounts")}>{t.accounts}</button><button className={page==="clusters"?"active":""} onClick={()=>setPage("clusters")}>{t.clusters}</button><button className={page==="method"?"active":""} onClick={()=>setPage("method")}>{t.method}</button></nav><div className="header-search" onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node|null))setSearchOpen(false);}}><span>⌕</span><input value={query} placeholder={t.search} aria-label={t.search} role="combobox" aria-expanded={searchOpen&&Boolean(query)} aria-controls="gid-suggestions" aria-autocomplete="list" aria-activedescendant={searchOpen&&suggestions[activeSuggestion]?`gid-option-${activeSuggestion}`:undefined} onFocus={()=>setSearchOpen(true)} onChange={e=>{const value=e.target.value.replace(/\D/g,"");setQuery(value);setActiveSuggestion(0);setSearchOpen(true);if(byGid.has(value))choose(value);}} onKeyDown={e=>{if(e.key==="Escape")setSearchOpen(false);if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();setSearchOpen(true);if(suggestions.length)setActiveSuggestion(i=>(i+(e.key==="ArrowDown"?1:-1)+suggestions.length)%suggestions.length);}if(e.key==="Enter"){e.preventDefault();const gid=byGid.has(query)?query:suggestions[activeSuggestion]?.gid;if(gid)choose(gid);}}}/>{searchOpen&&query&&<div className="search-menu" id="gid-suggestions" role="listbox">{!suggestions.length&&<p>{lang==="ru"?"Счёт не найден":"No account found"}</p>}{suggestions.map((n,index)=><button key={n.gid} id={`gid-option-${index}`} role="option" aria-selected={index===activeSuggestion} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(n.gid)}><span>{n.gid}<small>{ROLE_LABEL[lang][n.role]}</small></span><b style={{color:priorityColor(n.priority_score)}}>{n.priority_score.toFixed(3)}</b></button>)}</div>}</div><div className="lang"><button className={lang==="ru"?"active":""} onClick={()=>setLang("ru")}>RU</button><button className={lang==="en"?"active":""} onClick={()=>setLang("en")}>EN</button></div></header>
    <div className="data-strip"><span>{num(graph.meta.n_nodes,lang)} {lang==="ru"?"счетов":"accounts"} · {num(graph.meta.n_edges,lang)} {lang==="ru"?"связей":"directed links"} · {data.source==="pipeline"?(lang==="ru"?"Текущий анализ":"Generated analysis"):(lang==="ru"?"Демо-выгрузка":"Bundled snapshot")}</span><span>{t.limitationsText}</span></div>
    {data.sourceWarning&&<div className="analysis-warning" role="status">{lang==="ru"?"Локальная выгрузка неполна; показана демо-выгрузка. Отсутствуют: ":"Local analysis is incomplete; showing the bundled snapshot. Missing: "}{data.sourceWarning}</div>}
    {page==="accounts"&&<main className={`analyst-layout ${inspectorOpen?"":"inspector-collapsed"}`}>
      <aside className="queue"><div className="panel-title"><div><small>TOP PRIORITY</small><h2>{t.queue}</h2></div><button onClick={()=>setFilters(v=>!v)}>☷</button></div>{filters&&<div className="queue-filters"><label>{t.role}</label><select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="all">{t.all}</option>{ROLES.map(r=><option key={r} value={r}>{ROLE_LABEL[lang][r]}</option>)}</select><button onClick={()=>setRoleFilter("all")}>{t.reset}</button></div>}<div className="queue-list">{ordered.slice(0,30).map(n=><button key={n.gid} className={selected===n.gid?"selected":""} onClick={()=>choose(n.gid)}><i style={{background:priorityColor(n.priority_score)}}/><span><b>#{n.priority_rank} · {n.gid}</b><small>{ROLE_LABEL[lang][n.role]} · {money(Math.max(n.in_kzt,n.out_kzt),lang)}</small></span><strong style={{color:priorityColor(n.priority_score)}}>{n.priority_score.toFixed(3)}</strong></button>)}</div></aside>
      <section className="map-workspace"><div className="map-toolbar"><div className="mode-tabs"><button className={graphMode==="network"?"active":""} onClick={()=>focus("network")}>{t.network}</button><button className={graphMode==="connections"?"active":""} onClick={()=>focus("connections")} disabled={!selected}>{t.links}</button><button className={graphMode==="cluster"?"active":""} onClick={()=>focus("cluster")} disabled={!selected}>{t.cluster}</button>{activeRoute&&<button className={graphMode==="route"?"active":""} onClick={()=>focus("route")}>{lang==="ru"?"Маршрут":"Route"}</button>}</div><button className="inspector-toggle" aria-expanded={inspectorOpen} onClick={()=>setInspectorOpen(v=>!v)}>{inspectorOpen?(lang==="ru"?"Скрыть детали":"Hide details"):(lang==="ru"?"Открыть детали":"Show details")}</button></div><GraphMap graph={graph} nodeDetails={byGid} selectedGid={selected} focusToken={focusToken} mode={graphMode} roleFilter={roleFilter} onSelect={choose} language={lang} routeGids={activeRoute?.gids}/></section>
      <aside className="inspector" hidden={!inspectorOpen} aria-label={lang==="ru"?"Детали счёта":"Account details"} onKeyDown={e=>{if(e.key==="Escape")setInspectorOpen(false);}}>{selectedNode?<><div className="account-head"><button className="inspector-close" aria-label={lang==="ru"?"Закрыть детали":"Close account details"} onClick={()=>setInspectorOpen(false)}>×</button><small>GID · #{selectedNode.priority_rank}</small><h2>{selectedNode.gid}</h2><div><span className="role-chip">{ROLE_LABEL[lang][selectedNode.role]}</span>{selectedNode.is_seed&&<span className="seed-chip">SEED</span>}</div></div><section className="priority-hero" style={{borderColor:priorityColor(selectedNode.priority_score)}}><small>{t.priority}</small><div><strong style={{color:priorityColor(selectedNode.priority_score)}}>{selectedNode.priority_score.toFixed(3)}</strong><span style={{background:priorityColor(selectedNode.priority_score)}}>{priorityLabel(selectedNode.priority_score,lang)}</span></div></section><button className="focus-cta" onClick={()=>focus("connections")}>{t.show} →</button><section><h3>{priorityHeading(selectedNode.priority_score,lang)}</h3><p>{priorityReason(selectedNode,lang)}</p>{selectedNode.priority_why&&<div className="priority-explanation"><h4>{lang==="ru"?"Расчёт из выгрузки (EN)":"Exported ranking explanation"}</h4><p>{selectedNode.priority_why}</p></div>}</section><section><h3>{t.whyRole}</h3><p>{roleReason(selectedNode,lang)}</p></section><div className="key-metrics"><div><small>{t.inflow}</small><b>{money(selectedNode.in_kzt,lang)}</b></div><div><small>{t.outflow}</small><b>{money(selectedNode.out_kzt,lang)}</b></div><div><small>{selectedNode.is_seed?(lang==="ru"?"Получатели":"Recipients"):t.counterparties}</small><b>{selectedNode.distinct_counterparties}</b></div><div><small>{t.depth}</small><b>{selectedNode.depth}</b></div></div><InvestigationPanel key={selectedNode.gid} gid={selectedNode.gid} data={data.investigations} status={data.investigationStatus} language={lang} activeRoute={activeRoute} onRoute={showRoute} onClear={()=>focus("connections")} onAccount={choose}/>{selectedNode.is_seed&&<div className="warning"><p>{lang==="ru"?"Входящие переводы seed-счёта неполны. Приоритет использует исходящий оборот и число получателей.":"Seed inbound is incomplete. Priority uses observed outflow and recipient count."}</p></div>}<details><summary>{t.technical}</summary><h4>{lang==="ru"?"Основания роли":"Role evidence"}</h4><code>{selectedNode.evidence}</code><dl><dt>PageRank</dt><dd>{selectedNode.pagerank.toFixed(8)}</dd><dt>Betweenness</dt><dd>{selectedNode.betweenness.toFixed(8)}</dd><dt>Role score</dt><dd>{selectedNode.role_score.toFixed(3)}</dd>{selectedNode.top_rank&&<><dt>Top rank</dt><dd>#{selectedNode.top_rank}</dd></>}</dl></details>{selectedNode.truncated_by_depth&&<div className="warning"><b>{t.limitations}</b><p>{t.limitationsText}</p></div>}</>:<div className="inspector-empty">{t.select}</div>}</aside>
    </main>}
    {page==="clusters"&&<main className="cluster-page"><div className="page-heading"><h1>{t.clusters}</h1><p>{clusters.length} communities</p></div><div className="cluster-table">{rankedClusters.map(c=><article key={c.cluster_id}><div><small>CLUSTER</small><h2>#{c.cluster_id}</h2></div><dl><div><dt>{t.accounts}</dt><dd>{c.n_nodes}</dd></div><div><dt>{t.seeds}</dt><dd>{c.n_seed}</dd></div><div><dt>{t.internal}</dt><dd>{money(c.sum_kzt_internal,lang)}</dd></div></dl><details><summary>{t.hypothesis}</summary><p>{c.hypothesis}</p></details><button onClick={()=>{const gid=c.top_gids[0];if(gid)choose(gid);focus("cluster");}}>{t.openCluster} →</button></article>)}</div></main>}
    {page==="method"&&<main className="method-page"><small>METHODOLOGY</small><h1>{t.method}</h1><p>{t.methodText}</p><div className="priority-scale">{[["0–.24","#35a65a"],[".25–.49","#a8b83a"],[".50–.69","#e7b52c"],[".70–.84","#ea7a32"],[".85–1","#d64545"]].map(([label,color])=><span key={label} style={{background:color}}>{label}</span>)}</div><p>{t.limitationsText}</p></main>}
  </div>;
}
